[INFO    :   django.utils.autoreload] - 2024-01-14 14:26:21,197 : run_with_reloader @0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-14 14:26:23,517 : log_response @0241: Not Found: /
[WARNING :             django.server] - 2024-01-14 14:26:23,517 : log_message @0212: "GET / HTTP/1.1" 404 2167
[WARNING :            django.request] - 2024-01-14 14:26:23,764 : log_response @0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-14 14:26:23,767 : log_message @0212: "GET /favicon.ico HTTP/1.1" 404 2218
[DEBUG   :               app_1.views] - 2024-01-14 14:26:45,133 : index @0022: Index page requested.
[INFO    :             django.server] - 2024-01-14 14:26:45,134 : log_message @0212: "GET /hw_1/ HTTP/1.1" 200 284
[DEBUG   :               app_1.views] - 2024-01-14 14:27:46,224 : about @0040: About page requested.
[INFO    :             django.server] - 2024-01-14 14:27:46,224 : log_message @0212: "GET /hw_1/about/ HTTP/1.1" 200 266
[INFO    :   django.utils.autoreload] - 2024-01-14 14:49:43,235 : run_with_reloader @0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-14 14:49:48,968 : log_response @0241: Not Found: /
[WARNING :             django.server] - 2024-01-14 14:49:48,969 : log_message @0212: "GET / HTTP/1.1" 404 2167
[DEBUG   :               app_1.views] - 2024-01-14 14:50:13,040 : index @0022: Index page requested.
[INFO    :             django.server] - 2024-01-14 14:50:13,041 : log_message @0212: "GET /hw_1/ HTTP/1.1" 200 284
[DEBUG   :               app_1.views] - 2024-01-14 14:54:12,327 : index @0022: Index page requested.
[INFO    :             django.server] - 2024-01-14 14:54:12,328 : log_message @0212: "GET /hw_1/ HTTP/1.1" 200 284
[INFO    :   django.utils.autoreload] - 2024-01-23 17:30:50,663 : run_with_reloader @0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-23 17:31:01,659 : log_response @0241: Not Found: /
[WARNING :             django.server] - 2024-01-23 17:31:01,660 : log_message @0212: "GET / HTTP/1.1" 404 2274
[WARNING :            django.request] - 2024-01-23 17:31:01,751 : log_response @0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-23 17:31:01,752 : log_message @0212: "GET /favicon.ico HTTP/1.1" 404 2325
[INFO    :             django.server] - 2024-01-23 17:32:03,180 : log_message @0212: "GET /hw_2_3 HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-23 17:32:03,199 : log_message @0212: "GET /hw_2_3/ HTTP/1.1" 200 3646
[WARNING :            django.request] - 2024-01-23 17:32:17,316 : log_response @0241: Not Found: /
[WARNING :             django.server] - 2024-01-23 17:32:17,317 : log_message @0212: "GET / HTTP/1.1" 404 2274
[INFO    :   django.utils.autoreload] - 2024-01-23 17:34:10,686 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\homeworks\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 17:34:11,361 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 17:34:14,739 : log_message @0212: "GET / HTTP/1.1" 200 3646
[INFO    :             django.server] - 2024-01-23 17:34:16,175 : log_message @0212: "GET / HTTP/1.1" 200 3646
[INFO    :             django.server] - 2024-01-23 17:34:17,354 : log_message @0212: "GET / HTTP/1.1" 200 3646
[INFO    :             django.server] - 2024-01-23 17:34:19,056 : log_message @0212: "GET /shop/clients HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-23 17:34:19,077 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3701
[INFO    :             django.server] - 2024-01-23 17:34:35,222 : log_message @0212: "GET /shop/products HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-23 17:34:35,243 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5304
[INFO    :             django.server] - 2024-01-23 17:34:51,701 : log_message @0212: "GET /shop/orders HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-23 17:34:51,708 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 3950
[WARNING :            django.request] - 2024-01-23 17:35:00,166 : log_response @0241: Not Found: /about_me
[WARNING :             django.server] - 2024-01-23 17:35:00,167 : log_message @0212: "GET /about_me HTTP/1.1" 404 3742
[INFO    :             django.server] - 2024-01-23 17:35:09,994 : log_message @0212: "GET /admin HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-23 17:35:10,015 : log_message @0212: "GET /admin/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-23 17:35:10,120 : log_message @0212: "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
[INFO    :             django.server] - 2024-01-23 17:35:10,427 : log_message @0212: "GET /static/admin/css/login.css HTTP/1.1" 200 958
[INFO    :             django.server] - 2024-01-23 17:35:10,429 : log_message @0212: "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2682
[INFO    :             django.server] - 2024-01-23 17:35:10,433 : log_message @0212: "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
[INFO    :             django.server] - 2024-01-23 17:35:10,434 : log_message @0212: "GET /static/admin/css/base.css HTTP/1.1" 200 21544
[INFO    :             django.server] - 2024-01-23 17:35:10,435 : log_message @0212: "GET /static/admin/css/responsive.css HTTP/1.1" 200 17905
[INFO    :             django.server] - 2024-01-23 17:35:10,444 : log_message @0212: "GET /static/admin/js/theme.js HTTP/1.1" 200 1943
[INFO    :             django.server] - 2024-01-23 17:35:10,458 : log_message @0212: "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
[INFO    :   django.utils.autoreload] - 2024-01-23 17:38:52,622 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\homeworks\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 17:38:53,311 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 17:38:57,918 : log_message @0212: "GET /about_me HTTP/1.1" 301 0
[DEBUG   :               app_1.views] - 2024-01-23 17:38:57,924 : about @0040: About page requested.
[INFO    :             django.server] - 2024-01-23 17:38:57,924 : log_message @0212: "GET /about_me/ HTTP/1.1" 200 264
[DEBUG   :               app_1.views] - 2024-01-23 17:39:20,233 : about @0040: About page requested.
[INFO    :             django.server] - 2024-01-23 17:39:20,234 : log_message @0212: "GET /about_me/ HTTP/1.1" 200 264
[DEBUG   :               app_1.views] - 2024-01-23 17:41:33,178 : index @0022: Index page requested.
[INFO    :             django.server] - 2024-01-23 17:41:33,180 : log_message @0212: "GET / HTTP/1.1" 200 279
[INFO    :   django.utils.autoreload] - 2024-01-23 17:42:15,325 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_1\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 17:42:16,069 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 17:42:19,110 : log_message @0212: "GET / HTTP/1.1" 200 3646
[DEBUG   :               app_1.views] - 2024-01-23 17:42:22,988 : about @0040: About page requested.
[INFO    :             django.server] - 2024-01-23 17:42:22,989 : log_message @0212: "GET /about_me/ HTTP/1.1" 200 264
[INFO    :             django.server] - 2024-01-23 17:42:27,485 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3701
[INFO    :             django.server] - 2024-01-23 17:42:53,386 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5304
[INFO    :             django.server] - 2024-01-23 17:54:19,445 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5956
[INFO    :             django.server] - 2024-01-23 17:55:23,304 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5956
[WARNING :            django.request] - 2024-01-23 17:55:33,765 : log_response @0241: Not Found: /shop/choice_product_id_form
[WARNING :             django.server] - 2024-01-23 17:55:33,765 : log_message @0212: "GET /shop/choice_product_id_form HTTP/1.1" 404 3867
[INFO    :             django.server] - 2024-01-23 17:56:58,292 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5674
[INFO    :             django.server] - 2024-01-23 17:57:08,285 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 3668
[WARNING :            django.request] - 2024-01-23 18:08:13,355 : log_response @0241: Not Found: /shop/choice_products_by_client_by_days
[WARNING :             django.server] - 2024-01-23 18:08:13,356 : log_message @0212: "GET /shop/choice_products_by_client_by_days HTTP/1.1" 404 3900
[DEBUG   :               app_1.views] - 2024-01-23 18:08:19,310 : about @0040: About page requested.
[INFO    :             django.server] - 2024-01-23 18:08:19,311 : log_message @0212: "GET /about_me/ HTTP/1.1" 200 264
[INFO    :             django.server] - 2024-01-23 18:08:24,066 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 3668
[INFO    :             django.server] - 2024-01-23 18:13:06,075 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 3886
[INFO    :   django.utils.autoreload] - 2024-01-23 18:20:39,773 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 18:20:40,477 : run_with_reloader @0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-23 18:20:47,759 : log_response @0241: Not Found: /shop/choice_products_by_client_by_days
[WARNING :             django.server] - 2024-01-23 18:20:47,759 : log_message @0212: "GET /shop/choice_products_by_client_by_days HTTP/1.1" 404 3900
[INFO    :             django.server] - 2024-01-23 18:22:55,974 : log_message @0212: "GET /shop/client_products_sorted/3/7 HTTP/1.1" 301 0
[ERROR   :            django.request] - 2024-01-23 18:22:56,110 : log_response @0241: Internal Server Error: /shop/client_products_sorted/3/7/
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 82, in client_products_sorted
    orders = Order.objects.filter(buyer=client, date_create_order__range=(before, now)).all()
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1602, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1634, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1484, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1296, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1761, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'buyer' into field. Choices are: client, client_id, id, order_date, order_sum, product, product_id
[ERROR   :             django.server] - 2024-01-23 18:22:56,114 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 500 121886
[ERROR   :            django.request] - 2024-01-23 18:25:36,374 : log_response @0241: Internal Server Error: /shop/client_orders/3
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 57, in client_orders
    orders = Order.objects.filter(buyer=client).all()
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1602, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1634, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1484, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1296, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1761, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'buyer' into field. Choices are: client, client_id, id, order_date, order_sum, product, product_id
[ERROR   :             django.server] - 2024-01-23 18:25:36,377 : log_message @0212: "GET /shop/client_orders/3 HTTP/1.1" 500 120122
[INFO    :             django.server] - 2024-01-23 18:25:43,975 : log_message @0212: "GET / HTTP/1.1" 200 3360
[INFO    :             django.server] - 2024-01-23 18:25:46,851 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 3882
[INFO    :   django.utils.autoreload] - 2024-01-23 18:32:28,940 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 18:32:29,612 : run_with_reloader @0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-23 18:32:43,346 : log_response @0241: Internal Server Error: /shop/client_products_sorted/3/7/
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 82, in client_products_sorted
    orders = Order.objects.filter(client=client, date_create_order__range=(before, now)).all()
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1602, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1634, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1484, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1296, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1761, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_create_order' into field. Choices are: client, client_id, id, order_date, order_sum, product, product_id
[ERROR   :             django.server] - 2024-01-23 18:32:43,350 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 500 122685
[INFO    :   django.utils.autoreload] - 2024-01-23 18:40:47,098 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 18:40:47,692 : run_with_reloader @0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-23 18:40:52,169 : log_response @0241: Internal Server Error: /shop/client_products_sorted/3/7/
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 84, in client_products_sorted
    products = order.products.all()
AttributeError: 'Order' object has no attribute 'products'
[ERROR   :             django.server] - 2024-01-23 18:40:52,170 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 500 76103
[ERROR   :            django.request] - 2024-01-23 18:41:02,451 : log_response @0241: Internal Server Error: /shop/client_products_sorted/3/7/
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 84, in client_products_sorted
    products = order.products.all()
AttributeError: 'Order' object has no attribute 'products'
[ERROR   :             django.server] - 2024-01-23 18:41:02,452 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 500 76101
[INFO    :   django.utils.autoreload] - 2024-01-23 18:42:31,578 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 18:42:32,128 : run_with_reloader @0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-23 18:42:36,628 : log_response @0241: Internal Server Error: /shop/client_products_sorted/3/7/
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 84, in client_products_sorted
    products = order.product.all()
AttributeError: 'Product' object has no attribute 'all'
[ERROR   :             django.server] - 2024-01-23 18:42:36,630 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 500 76089
[INFO    :   django.utils.autoreload] - 2024-01-23 18:46:43,990 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 18:46:44,576 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-23 18:48:03,348 : run_with_reloader @0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-23 18:48:03,560 : log_response @0241: Internal Server Error: /shop/client_products_sorted/3/7/
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 84, in client_products_sorted
    products = order.product.all()
AttributeError: 'Product' object has no attribute 'all'
[ERROR   :             django.server] - 2024-01-23 18:48:03,560 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 500 76087
[INFO    :   django.utils.autoreload] - 2024-01-23 18:49:45,098 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 18:49:45,737 : run_with_reloader @0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-23 18:49:47,006 : log_response @0241: Internal Server Error: /shop/client_products_sorted/3/7/
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 84, in client_products_sorted
    products = order.products.all()
AttributeError: 'Order' object has no attribute 'products'
[ERROR   :             django.server] - 2024-01-23 18:49:47,008 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 500 76103
[INFO    :   django.utils.autoreload] - 2024-01-23 18:50:49,887 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 18:50:50,434 : run_with_reloader @0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-23 18:50:53,481 : log_response @0241: Internal Server Error: /shop/client_products_sorted/3/7/
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 84, in client_products_sorted
    products = order.product.all()
AttributeError: 'Product' object has no attribute 'all'
[ERROR   :             django.server] - 2024-01-23 18:50:53,482 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 500 76089
[INFO    :   django.utils.autoreload] - 2024-01-23 18:53:48,417 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 18:53:49,031 : run_with_reloader @0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-23 18:53:52,215 : log_response @0241: Internal Server Error: /shop/client_products_sorted/3/7/
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 85, in client_products_sorted
    for product in products:
TypeError: 'Product' object is not iterable
[ERROR   :             django.server] - 2024-01-23 18:53:52,217 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 500 76056
[INFO    :   django.utils.autoreload] - 2024-01-23 18:56:25,860 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 18:58:20,788 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 18:58:24,827 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 200 3370
[INFO    :   django.utils.autoreload] - 2024-01-23 19:07:59,628 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 19:08:09,648 : log_message @0212: "GET /shop/client_products_sorted/3/1/ HTTP/1.1" 200 3490
[INFO    :             django.server] - 2024-01-23 19:08:43,656 : log_message @0212: "GET /shop/client_products_sorted/3/4/ HTTP/1.1" 200 3490
[INFO    :             django.server] - 2024-01-23 19:08:53,670 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 200 3490
[INFO    :             django.server] - 2024-01-23 19:09:01,738 : log_message @0212: "GET /shop/client_products_sorted/3/1/ HTTP/1.1" 200 3490
[INFO    :   django.utils.autoreload] - 2024-01-23 19:12:38,642 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 19:12:45,004 : log_message @0212: "GET /shop/client_products_sorted/3/1/ HTTP/1.1" 200 3490
[INFO    :             django.server] - 2024-01-23 19:12:55,389 : log_message @0212: "GET /shop/client_products_sorted/3/5/ HTTP/1.1" 200 3490
[INFO    :             django.server] - 2024-01-23 19:13:04,317 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 200 3490
[INFO    :             django.server] - 2024-01-23 19:13:21,575 : log_message @0212: "GET /shop/client_products_sorted/3/30/ HTTP/1.1" 200 3492
[INFO    :             django.server] - 2024-01-23 19:14:08,470 : log_message @0212: "GET /shop/client_products_sorted/3/30/ HTTP/1.1" 200 3372
[INFO    :             django.server] - 2024-01-23 19:14:09,241 : log_message @0212: "GET /shop/client_products_sorted/3/30/ HTTP/1.1" 200 3372
[INFO    :             django.server] - 2024-01-23 20:24:05,861 : log_message @0212: "GET /shop/client_products_sorted/3/30/ HTTP/1.1" 200 3248
[INFO    :             django.server] - 2024-01-23 20:24:47,306 : log_message @0212: "GET /shop/client_products_sorted/3/30/ HTTP/1.1" 200 3074
[INFO    :   django.utils.autoreload] - 2024-01-23 20:37:28,431 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 20:37:29,125 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-23 20:51:06,366 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 20:51:11,084 : log_message @0212: "GET /shop/client_products_sorted/3/30/ HTTP/1.1" 200 3434
[INFO    :   django.utils.autoreload] - 2024-01-23 20:59:31,046 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 20:59:31,678 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-23 21:04:08,587 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 21:04:24,689 : log_message @0212: "GET /shop/client_products_sorted/3/0/ HTTP/1.1" 200 3072
[INFO    :             django.server] - 2024-01-23 21:04:33,768 : log_message @0212: "GET /shop/client_products_sorted/3/1/ HTTP/1.1" 200 3313
[INFO    :             django.server] - 2024-01-23 21:05:00,053 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3117
[INFO    :             django.server] - 2024-01-23 21:05:05,452 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5372
[INFO    :             django.server] - 2024-01-23 21:05:09,318 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 3778
[INFO    :             django.server] - 2024-01-23 21:05:32,672 : log_message @0212: "GET /shop/client_products_sorted/3/7/ HTTP/1.1" 200 3313
[INFO    :   django.utils.autoreload] - 2024-01-23 21:08:49,401 : run_with_reloader @0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-23 21:10:15,086 : log_response @0241: Internal Server Error: /shop/client_orders/3
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 60, in client_orders
    products[order.id] = str(order.products.all()).replace('<QuerySet [<', '').replace('>]>',
AttributeError: 'Order' object has no attribute 'products'
[ERROR   :             django.server] - 2024-01-23 21:10:15,087 : log_message @0212: "GET /shop/client_orders/3 HTTP/1.1" 500 74948
[INFO    :   django.utils.autoreload] - 2024-01-23 21:11:13,744 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 21:11:14,433 : run_with_reloader @0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-23 21:11:18,184 : log_response @0241: Internal Server Error: /shop/client_orders/3
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 63, in client_orders
    return render(request, 'app_2/client_orders.html', {'client': client, 'orders': orders,
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: app_2/client_orders.html
[ERROR   :             django.server] - 2024-01-23 21:11:18,187 : log_message @0212: "GET /shop/client_orders/3 HTTP/1.1" 500 91653
[INFO    :             django.server] - 2024-01-23 21:13:43,108 : log_message @0212: "GET /shop/client_orders/3 HTTP/1.1" 200 3966
[INFO    :             django.server] - 2024-01-23 21:18:53,261 : log_message @0212: "GET /shop/client_orders/3 HTTP/1.1" 200 3989
[INFO    :             django.server] - 2024-01-23 21:22:36,842 : log_message @0212: "GET /shop/client_orders/3 HTTP/1.1" 200 3994
[INFO    :             django.server] - 2024-01-23 21:23:52,634 : log_message @0212: "GET /shop/orders HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-23 21:23:52,646 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 3778
[INFO    :   django.utils.autoreload] - 2024-01-23 21:27:38,749 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 21:27:43,689 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 3796
[INFO    :   django.utils.autoreload] - 2024-01-23 21:28:53,227 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 21:28:53,813 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-23 21:29:38,008 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 21:29:38,662 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 21:29:44,740 : log_message @0212: "GET /shop/client_orders/3 HTTP/1.1" 200 4012
[INFO    :             django.server] - 2024-01-23 21:30:35,606 : log_message @0212: "GET /shop/client_orders/1 HTTP/1.1" 200 3070
[INFO    :             django.server] - 2024-01-23 21:30:43,267 : log_message @0212: "GET /shop/client_orders/3 HTTP/1.1" 200 4012
[INFO    :   django.utils.autoreload] - 2024-01-23 21:31:19,483 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 21:31:20,141 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-23 21:38:27,102 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 21:38:34,689 : log_message @0212: "GET /shop/client_orders/5 HTTP/1.1" 200 4010
[INFO    :             django.server] - 2024-01-23 21:39:21,405 : log_message @0212: "GET /shop/client_products_sorted/5/0 HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-23 21:39:21,414 : log_message @0212: "GET /shop/client_products_sorted/5/0/ HTTP/1.1" 200 3312
[INFO    :             django.server] - 2024-01-23 21:39:46,379 : log_message @0212: "GET /shop/client_products_sorted/5/1/ HTTP/1.1" 200 3312
[INFO    :             django.server] - 2024-01-23 21:39:57,630 : log_message @0212: "GET /shop/client_products_sorted/5/0/ HTTP/1.1" 200 3312
[INFO    :             django.server] - 2024-01-23 21:40:04,781 : log_message @0212: "GET /shop/client_products_sorted/5/2/ HTTP/1.1" 200 3312
[INFO    :   django.utils.autoreload] - 2024-01-23 21:42:57,767 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 21:42:58,357 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 21:43:26,154 : log_message @0212: "GET /shop/order/22 HTTP/1.1" 200 3018
[INFO    :             django.server] - 2024-01-23 21:45:33,416 : log_message @0212: "GET /shop/order/22 HTTP/1.1" 200 3095
[INFO    :   django.utils.autoreload] - 2024-01-23 21:50:02,225 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 21:50:02,953 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 21:50:04,380 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3117
[INFO    :   django.utils.autoreload] - 2024-01-23 21:50:40,047 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 21:50:40,662 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 21:51:59,218 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3122
[INFO    :             django.server] - 2024-01-23 21:52:41,282 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3133
[INFO    :             django.server] - 2024-01-23 21:53:16,883 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3104
[INFO    :             django.server] - 2024-01-23 21:53:24,277 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5380
[INFO    :             django.server] - 2024-01-23 21:53:32,775 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 3794
[INFO    :             django.server] - 2024-01-23 21:53:38,470 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3104
[INFO    :             django.server] - 2024-01-23 21:53:42,132 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 3794
[INFO    :             django.server] - 2024-01-23 21:53:51,401 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5380
[INFO    :             django.server] - 2024-01-23 21:53:55,144 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3104
[INFO    :   django.utils.autoreload] - 2024-01-23 21:56:27,220 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 21:56:53,723 : log_message @0212: "GET /shop/client_products_sorted/6/1 HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-23 21:56:53,739 : log_message @0212: "GET /shop/client_products_sorted/6/1/ HTTP/1.1" 200 3190
[INFO    :             django.server] - 2024-01-23 21:57:09,859 : log_message @0212: "GET /shop/client_products_sorted/5/1/ HTTP/1.1" 200 3312
[INFO    :             django.server] - 2024-01-23 21:57:18,561 : log_message @0212: "GET /shop/client_products_sorted/5/0/ HTTP/1.1" 200 3312
[WARNING :            django.request] - 2024-01-23 21:57:27,494 : log_response @0241: Not Found: /shop/client_products_sorted/5/-1/
[WARNING :             django.server] - 2024-01-23 21:57:27,495 : log_message @0212: "GET /shop/client_products_sorted/5/-1/ HTTP/1.1" 404 3693
[INFO    :             django.server] - 2024-01-23 21:57:36,957 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3211
[INFO    :             django.server] - 2024-01-23 21:57:47,917 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5380
[INFO    :             django.server] - 2024-01-23 21:57:50,877 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 4190
[DEBUG   :               app_1.views] - 2024-01-23 21:58:06,787 : about @0040: About page requested.
[INFO    :             django.server] - 2024-01-23 21:58:06,787 : log_message @0212: "GET /about_me/ HTTP/1.1" 200 264
[INFO    :             django.server] - 2024-01-23 21:58:13,774 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3211
[INFO    :             django.server] - 2024-01-23 21:58:19,828 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3211
[INFO    :             django.server] - 2024-01-23 21:58:22,228 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5380
[INFO    :             django.server] - 2024-01-23 21:58:25,346 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 4190
[INFO    :             django.server] - 2024-01-23 21:58:28,923 : log_message @0212: "GET / HTTP/1.1" 200 3062
[INFO    :   django.utils.autoreload] - 2024-01-23 22:04:18,726 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 22:05:04,302 : log_message @0212: "GET /shop/client_orders/5 HTTP/1.1" 200 4010
[INFO    :   django.utils.autoreload] - 2024-01-24 11:48:36,688 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-24 11:49:11,355 : log_message @0212: "GET /shop/client_products_sorted/6/1 HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-24 11:49:11,399 : log_message @0212: "GET /shop/client_products_sorted/6/1/ HTTP/1.1" 200 3190
[WARNING :            django.request] - 2024-01-24 11:49:11,496 : log_response @0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-24 11:49:11,497 : log_message @0212: "GET /favicon.ico HTTP/1.1" 404 3627
[INFO    :             django.server] - 2024-01-24 11:49:20,686 : log_message @0212: "GET /shop/client_products_sorted/6/2/ HTTP/1.1" 200 3190
[INFO    :             django.server] - 2024-01-24 11:49:29,784 : log_message @0212: "GET /shop/client_products_sorted/6/3/ HTTP/1.1" 200 3190
[INFO    :             django.server] - 2024-01-24 11:49:38,180 : log_message @0212: "GET /shop/client_products_sorted/6/4/ HTTP/1.1" 200 3190
[INFO    :   django.utils.autoreload] - 2024-01-24 11:51:45,411 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-24 11:51:54,477 : log_message @0212: "GET /shop/client_products_sorted/6/1/ HTTP/1.1" 200 3310
[INFO    :             django.server] - 2024-01-24 11:52:08,872 : log_message @0212: "GET /shop/client_products_sorted/6/2/ HTTP/1.1" 200 3310
[INFO    :             django.server] - 2024-01-24 11:52:18,724 : log_message @0212: "GET /shop/client_products_sorted/6/3/ HTTP/1.1" 200 3310
[INFO    :   django.utils.autoreload] - 2024-01-24 11:55:22,272 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-24 11:55:37,831 : log_message @0212: "GET /shop/client_products_sorted/5/1/ HTTP/1.1" 200 3432
[INFO    :             django.server] - 2024-01-24 11:56:01,254 : log_message @0212: "GET /shop/client_products_sorted/5/0/ HTTP/1.1" 200 3192
[INFO    :   django.utils.autoreload] - 2024-01-28 15:01:22,660 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-28 15:04:56,918 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-28 15:04:57,517 : run_with_reloader @0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-28 15:05:00,979 : log_response @0241: Not Found: /shop/product_form/11/
[WARNING :             django.server] - 2024-01-28 15:05:00,980 : log_message @0212: "GET /shop/product_form/11/ HTTP/1.1" 404 3865
[WARNING :            django.request] - 2024-01-28 15:05:01,214 : log_response @0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-28 15:05:01,215 : log_message @0212: "GET /favicon.ico HTTP/1.1" 404 3835
[INFO    :   django.utils.autoreload] - 2024-01-28 15:15:46,472 : run_with_reloader @0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-28 15:16:42,155 : log_response @0241: Not Found: /shop/product_form/1/
[WARNING :             django.server] - 2024-01-28 15:16:42,156 : log_message @0212: "GET /shop/product_form/1/ HTTP/1.1" 404 3862
[WARNING :            django.request] - 2024-01-28 15:16:48,289 : log_response @0241: Not Found: /shop/product_form/17/
[WARNING :             django.server] - 2024-01-28 15:16:48,289 : log_message @0212: "GET /shop/product_form/17/ HTTP/1.1" 404 3865
[WARNING :            django.request] - 2024-01-28 15:16:50,288 : log_response @0241: Not Found: /shop/product_form/17/
[WARNING :             django.server] - 2024-01-28 15:16:50,288 : log_message @0212: "GET /shop/product_form/17/ HTTP/1.1" 404 3865
[ERROR   :            django.request] - 2024-01-28 15:17:11,933 : log_response @0241: Internal Server Error: /shop/product_form/17
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: app_2_product.image_product

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 86, in product_form
    product = get_object_or_404(Product, pk=id_product)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 643, in get
    num = len(clone)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1926, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: app_2_product.image_product
[ERROR   :             django.server] - 2024-01-28 15:17:11,937 : log_message @0212: "GET /shop/product_form/17 HTTP/1.1" 500 145770
[ERROR   :            django.request] - 2024-01-28 15:17:21,992 : log_response @0241: Internal Server Error: /shop/product_form/11
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: app_2_product.image_product

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 86, in product_form
    product = get_object_or_404(Product, pk=id_product)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 643, in get
    num = len(clone)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1926, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: app_2_product.image_product
[ERROR   :             django.server] - 2024-01-28 15:17:21,996 : log_message @0212: "GET /shop/product_form/11 HTTP/1.1" 500 145770
[INFO    :   django.utils.autoreload] - 2024-01-28 15:18:45,825 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-28 15:18:46,494 : run_with_reloader @0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-28 15:18:52,760 : log_response @0241: Internal Server Error: /shop/product_form/11/
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: app_2_product.image_product

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 86, in product_form
    product = get_object_or_404(Product, pk=id_product)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 643, in get
    num = len(clone)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1926, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: app_2_product.image_product
[ERROR   :             django.server] - 2024-01-28 15:18:52,765 : log_message @0212: "GET /shop/product_form/11/ HTTP/1.1" 500 145780
[INFO    :   django.utils.autoreload] - 2024-01-28 15:21:11,127 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-28 15:21:11,681 : run_with_reloader @0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-28 15:21:16,745 : log_response @0241: Internal Server Error: /shop/product_form/11/
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: app_2_product.image_product

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 86, in product_form
    product = get_object_or_404(Product, pk=id_product)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 643, in get
    num = len(clone)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1926, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: app_2_product.image_product
[ERROR   :             django.server] - 2024-01-28 15:21:16,750 : log_message @0212: "GET /shop/product_form/11/ HTTP/1.1" 500 145917
[INFO    :   django.utils.autoreload] - 2024-01-28 15:22:02,476 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-28 15:22:03,056 : run_with_reloader @0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-28 15:24:20,082 : log_response @0241: Internal Server Error: /shop/product_form/11/
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: app_2_product.image_product

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 86, in product_form
    product = get_object_or_404(Product, pk=id_product)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 643, in get
    num = len(clone)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1926, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: app_2_product.image_product
[ERROR   :             django.server] - 2024-01-28 15:24:20,086 : log_message @0212: "GET /shop/product_form/11/ HTTP/1.1" 500 145917
[INFO    :   django.utils.autoreload] - 2024-01-28 15:45:52,707 : run_with_reloader @0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-28 15:46:07,434 : log_response @0241: Internal Server Error: /shop/product_form/1/
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py", line 109, in product_form
    return render(request, "product_form.html", context=context)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: product_form.html
[ERROR   :             django.server] - 2024-01-28 15:46:07,436 : log_message @0212: "GET /shop/product_form/1/ HTTP/1.1" 500 90143
[INFO    :   django.utils.autoreload] - 2024-01-28 15:48:32,158 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-28 15:48:32,712 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-28 15:48:37,055 : log_message @0212: "GET /shop/product_form/1/ HTTP/1.1" 200 4179
[INFO    :             django.server] - 2024-01-28 15:52:01,113 : log_message @0212: "POST /shop/product_form/1/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-28 15:52:01,132 : log_message @0212: "GET /shop/product/1 HTTP/1.1" 200 3175
[INFO    :             django.server] - 2024-01-28 15:54:00,613 : log_message @0212: "GET /shop/products HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-28 15:54:00,631 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5385
[INFO    :             django.server] - 2024-01-28 15:54:05,623 : log_message @0212: "GET /shop/orders HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-28 15:54:05,640 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 2998
[INFO    :             django.server] - 2024-01-28 15:54:07,929 : log_message @0212: "GET /about_me HTTP/1.1" 301 0
[DEBUG   :               app_1.views] - 2024-01-28 15:54:07,936 : about @0040: About page requested.
[INFO    :             django.server] - 2024-01-28 15:54:07,936 : log_message @0212: "GET /about_me/ HTTP/1.1" 200 264
[INFO    :             django.server] - 2024-01-28 15:54:13,319 : log_message @0212: "GET / HTTP/1.1" 200 3062
[INFO    :             django.server] - 2024-01-28 15:54:16,013 : log_message @0212: "GET /shop/clients HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-28 15:54:16,025 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3104
[INFO    :             django.server] - 2024-01-28 15:54:21,509 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5385
[INFO    :   django.utils.autoreload] - 2024-01-28 15:57:28,620 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-28 15:57:34,157 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 3427
[INFO    :             django.server] - 2024-01-28 15:57:43,057 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5385
[INFO    :             django.server] - 2024-01-28 15:57:45,231 : log_message @0212: "GET /shop/clients/ HTTP/1.1" 200 3104
[INFO    :             django.server] - 2024-01-28 15:57:51,091 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5385
[INFO    :   django.utils.autoreload] - 2024-01-28 16:00:01,902 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-28 16:00:02,497 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-28 16:00:08,037 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-28 16:00:25,199 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\forms.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-28 16:00:42,298 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-28 16:01:19,139 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-28 16:01:19,761 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-28 16:02:27,791 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-28 16:03:09,365 : log_message @0212: "GET /shop/product_form/1/ HTTP/1.1" 200 4179
[INFO    :             django.server] - 2024-01-28 16:03:22,953 : log_message @0212: "GET /shop/product_form/2/ HTTP/1.1" 200 4179
[INFO    :             django.server] - 2024-01-28 16:04:35,740 : log_message @0212: "POST /shop/product_form/2/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-28 16:04:35,759 : log_message @0212: "GET /shop/product/2 HTTP/1.1" 200 3182
[INFO    :             django.server] - 2024-01-28 16:04:42,831 : log_message @0212: "GET /shop/products/ HTTP/1.1" 200 5395
[INFO    :             django.server] - 2024-01-28 16:04:51,869 : log_message @0212: "GET /shop/orders/ HTTP/1.1" 200 3427
[INFO    :   django.utils.autoreload] - 2024-01-31 16:29:18,562 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-31 16:29:43,797 : log_message @0212: "GET /admin/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 16:29:43,900 : log_message @0212: "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
[INFO    :             django.server] - 2024-01-31 16:29:50,155 : log_message @0212: "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 16:29:50,184 : log_message @0212: "GET /admin/ HTTP/1.1" 200 5533
[INFO    :   django.utils.autoreload] - 2024-01-31 16:30:37,554 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\homeworks\settings.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-31 16:30:38,168 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-31 16:30:40,965 : log_message @0212: "GET /admin/ HTTP/1.1" 200 5944
[INFO    :             django.server] - 2024-01-31 16:35:09,514 : log_message @0212: "GET /admin/auth/group/add/ HTTP/1.1" 200 12862
[INFO    :             django.server] - 2024-01-31 16:35:09,570 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:35:09,690 : log_message @0212: "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4530
[INFO    :             django.server] - 2024-01-31 16:35:09,691 : log_message @0212: "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15492
[INFO    :             django.server] - 2024-01-31 16:35:09,750 : log_message @0212: "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
[INFO    :             django.server] - 2024-01-31 16:35:09,750 : log_message @0212: "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
[INFO    :             django.server] - 2024-01-31 16:35:09,758 : log_message @0212: "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
[INFO    :             django.server] - 2024-01-31 16:44:53,568 : log_message @0212: "POST /admin/auth/group/add/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 16:44:53,589 : log_message @0212: "GET /admin/auth/group/add/ HTTP/1.1" 200 13150
[INFO    :             django.server] - 2024-01-31 16:44:53,623 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:45:19,476 : log_message @0212: "POST /admin/auth/group/add/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 16:45:19,498 : log_message @0212: "GET /admin/auth/group/add/ HTTP/1.1" 200 13149
[INFO    :             django.server] - 2024-01-31 16:45:19,533 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:45:34,699 : log_message @0212: "POST /admin/auth/group/add/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 16:45:34,758 : log_message @0212: "GET /admin/auth/group/ HTTP/1.1" 200 10158
[INFO    :             django.server] - 2024-01-31 16:45:34,788 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:45:37,619 : log_message @0212: "GET /admin/auth/group/2/change/ HTTP/1.1" 200 13067
[INFO    :             django.server] - 2024-01-31 16:45:37,650 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:45:55,363 : log_message @0212: "GET /admin/auth/group/ HTTP/1.1" 200 9947
[INFO    :             django.server] - 2024-01-31 16:45:55,392 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:45:56,529 : log_message @0212: "GET /admin/auth/group/1/change/ HTTP/1.1" 200 13098
[INFO    :             django.server] - 2024-01-31 16:45:56,559 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:46:06,353 : log_message @0212: "POST /admin/auth/group/1/change/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 16:46:06,370 : log_message @0212: "GET /admin/auth/group/ HTTP/1.1" 200 10159
[INFO    :             django.server] - 2024-01-31 16:46:06,401 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:46:08,336 : log_message @0212: "GET /admin/auth/group/2/change/ HTTP/1.1" 200 13067
[INFO    :             django.server] - 2024-01-31 16:46:08,366 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:46:15,680 : log_message @0212: "POST /admin/auth/group/2/change/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 16:46:15,697 : log_message @0212: "GET /admin/auth/group/ HTTP/1.1" 200 10158
[INFO    :             django.server] - 2024-01-31 16:46:15,728 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:46:17,183 : log_message @0212: "GET /admin/auth/group/3/change/ HTTP/1.1" 200 13111
[INFO    :             django.server] - 2024-01-31 16:46:17,212 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:46:19,010 : log_message @0212: "POST /admin/auth/group/3/change/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 16:46:19,030 : log_message @0212: "GET /admin/auth/group/ HTTP/1.1" 200 10160
[INFO    :             django.server] - 2024-01-31 16:46:19,058 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:46:22,643 : log_message @0212: "GET /admin/auth/user/add/ HTTP/1.1" 200 11238
[INFO    :             django.server] - 2024-01-31 16:46:22,676 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:46:51,945 : log_message @0212: "POST /admin/auth/user/add/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 16:46:52,000 : log_message @0212: "GET /admin/auth/user/2/change/ HTTP/1.1" 200 23892
[INFO    :             django.server] - 2024-01-31 16:46:52,036 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:46:52,052 : log_message @0212: "GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
[INFO    :             django.server] - 2024-01-31 16:46:52,054 : log_message @0212: "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
[INFO    :             django.server] - 2024-01-31 16:46:52,119 : log_message @0212: "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
[INFO    :             django.server] - 2024-01-31 16:46:52,127 : log_message @0212: "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
[INFO    :             django.server] - 2024-01-31 16:47:22,767 : log_message @0212: "POST /admin/auth/user/2/change/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 16:47:22,795 : log_message @0212: "GET /admin/auth/user/ HTTP/1.1" 200 13098
[INFO    :             django.server] - 2024-01-31 16:47:22,829 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:47:27,848 : log_message @0212: "GET /admin/auth/user/add/ HTTP/1.1" 200 11238
[INFO    :             django.server] - 2024-01-31 16:47:27,878 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:47:48,869 : log_message @0212: "POST /admin/auth/user/add/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 16:47:48,901 : log_message @0212: "GET /admin/auth/user/3/change/ HTTP/1.1" 200 23887
[INFO    :             django.server] - 2024-01-31 16:47:48,935 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:48:05,469 : log_message @0212: "POST /admin/auth/user/3/change/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 16:48:05,490 : log_message @0212: "GET /admin/auth/user/ HTTP/1.1" 200 13616
[INFO    :             django.server] - 2024-01-31 16:48:05,549 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:48:05,554 : log_message @0212: "GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
[INFO    :             django.server] - 2024-01-31 16:48:07,960 : log_message @0212: "GET /admin/auth/user/add/ HTTP/1.1" 200 11238
[INFO    :             django.server] - 2024-01-31 16:48:07,993 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:48:25,746 : log_message @0212: "POST /admin/auth/user/add/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 16:48:25,776 : log_message @0212: "GET /admin/auth/user/4/change/ HTTP/1.1" 200 23897
[INFO    :             django.server] - 2024-01-31 16:48:25,825 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:48:40,660 : log_message @0212: "POST /admin/auth/user/4/change/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 16:48:40,681 : log_message @0212: "GET /admin/auth/user/ HTTP/1.1" 200 14141
[INFO    :             django.server] - 2024-01-31 16:48:40,716 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:48:44,269 : log_message @0212: "GET /admin/auth/user/3/change/ HTTP/1.1" 200 23626
[INFO    :             django.server] - 2024-01-31 16:48:44,295 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:48:49,378 : log_message @0212: "POST /admin/auth/user/3/change/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 16:48:49,398 : log_message @0212: "GET /admin/auth/user/ HTTP/1.1" 200 14139
[INFO    :             django.server] - 2024-01-31 16:48:49,434 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:48:50,906 : log_message @0212: "GET /admin/auth/user/4/change/ HTTP/1.1" 200 23634
[INFO    :             django.server] - 2024-01-31 16:48:50,936 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:48:59,236 : log_message @0212: "POST /admin/auth/user/4/change/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 16:48:59,254 : log_message @0212: "GET /admin/auth/user/ HTTP/1.1" 200 14141
[INFO    :             django.server] - 2024-01-31 16:48:59,284 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 16:50:51,212 : log_message @0212: "POST /admin/logout/ HTTP/1.1" 200 3817
[INFO    :             django.server] - 2024-01-31 16:50:52,606 : log_message @0212: "GET /admin/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 16:50:52,617 : log_message @0212: "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
[INFO    :             django.server] - 2024-01-31 16:51:04,102 : log_message @0212: "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 16:51:04,113 : log_message @0212: "GET /admin/ HTTP/1.1" 200 4899
[INFO    :   django.utils.autoreload] - 2024-01-31 16:52:37,076 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-31 16:52:37,738 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-31 16:53:47,025 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-31 16:53:47,571 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-31 16:56:35,568 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-31 16:56:36,216 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-31 16:56:57,595 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-31 16:56:58,169 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-31 17:07:20,435 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-31 17:08:26,417 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-31 17:08:26,982 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-31 17:08:36,370 : log_message @0212: "GET /admin/ HTTP/1.1" 200 5436
[INFO    :             django.server] - 2024-01-31 17:08:41,720 : log_message @0212: "GET /admin/app_2/order/ HTTP/1.1" 200 11605
[INFO    :             django.server] - 2024-01-31 17:08:41,755 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 17:09:12,330 : log_message @0212: "GET /admin/app_2/order/1/change/ HTTP/1.1" 200 12246
[INFO    :             django.server] - 2024-01-31 17:09:12,364 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 17:09:18,217 : log_message @0212: "POST /admin/app_2/order/1/change/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 17:09:18,238 : log_message @0212: "GET /admin/app_2/order/ HTTP/1.1" 200 11872
[INFO    :             django.server] - 2024-01-31 17:09:18,273 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 17:09:31,938 : log_message @0212: "POST /admin/app_2/order/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 17:09:31,959 : log_message @0212: "GET /admin/app_2/order/ HTTP/1.1" 200 11875
[INFO    :             django.server] - 2024-01-31 17:09:31,994 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 17:09:32,084 : log_message @0212: "GET /static/admin/img/icon-alert.svg HTTP/1.1" 200 504
[INFO    :             django.server] - 2024-01-31 17:09:40,487 : log_message @0212: "POST /admin/app_2/order/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 17:09:40,507 : log_message @0212: "GET /admin/app_2/order/ HTTP/1.1" 200 11605
[INFO    :             django.server] - 2024-01-31 17:09:40,538 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 17:09:53,964 : log_message @0212: "POST /admin/logout/ HTTP/1.1" 200 3817
[INFO    :             django.server] - 2024-01-31 17:09:55,152 : log_message @0212: "GET /admin/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 17:09:55,166 : log_message @0212: "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
[INFO    :             django.server] - 2024-01-31 17:10:01,701 : log_message @0212: "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 17:10:01,718 : log_message @0212: "GET /admin/ HTTP/1.1" 200 11283
[INFO    :             django.server] - 2024-01-31 17:10:20,460 : log_message @0212: "GET /admin/app_2/client/ HTTP/1.1" 200 11257
[INFO    :             django.server] - 2024-01-31 17:10:20,493 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 17:10:22,616 : log_message @0212: "GET /admin/app_2/order/ HTTP/1.1" 200 13116
[INFO    :             django.server] - 2024-01-31 17:10:22,644 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 17:10:26,023 : log_message @0212: "GET /admin/app_2/product/ HTTP/1.1" 200 18136
[INFO    :             django.server] - 2024-01-31 17:10:26,052 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 17:10:42,522 : log_message @0212: "POST /admin/app_2/product/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 17:10:42,547 : log_message @0212: "GET /admin/app_2/product/ HTTP/1.1" 200 18136
[INFO    :             django.server] - 2024-01-31 17:10:42,577 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 17:11:11,350 : log_message @0212: "GET /admin/app_2/order/ HTTP/1.1" 200 13116
[INFO    :             django.server] - 2024-01-31 17:11:11,390 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-31 17:11:11,915 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-31 17:11:12,503 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-31 17:11:13,749 : log_message @0212: "GET /admin/app_2/order/1/change/ HTTP/1.1" 200 15132
[INFO    :             django.server] - 2024-01-31 17:11:13,808 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-31 17:12:34,248 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-31 17:12:34,828 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-31 17:12:38,383 : log_message @0212: "POST /admin/app_2/order/1/change/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 17:12:38,450 : log_message @0212: "GET /admin/app_2/order/ HTTP/1.1" 200 13383
[INFO    :             django.server] - 2024-01-31 17:12:38,489 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 17:12:41,497 : log_message @0212: "GET /admin/app_2/order/1/change/ HTTP/1.1" 200 15153
[INFO    :             django.server] - 2024-01-31 17:12:41,529 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 17:13:13,495 : log_message @0212: "GET /admin/app_2/order/ HTTP/1.1" 200 13116
[INFO    :             django.server] - 2024-01-31 17:13:13,529 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-31 17:13:48,590 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-31 17:13:49,187 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-31 17:13:52,528 : log_message @0212: "GET /admin/app_2/order/ HTTP/1.1" 200 13116
[INFO    :             django.server] - 2024-01-31 17:13:52,557 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 17:14:03,349 : log_message @0212: "GET /admin/app_2/product/ HTTP/1.1" 200 18136
[INFO    :             django.server] - 2024-01-31 17:14:03,384 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[ERROR   :            django.request] - 2024-01-31 17:14:23,785 : log_response @0241: Internal Server Error: /admin/app_2/product/
Traceback (most recent call last):
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\contrib\admin\options.py", line 714, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\contrib\admin\options.py", line 1981, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\contrib\admin\options.py", line 862, in get_changelist_instance
    return ChangeList(
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\contrib\admin\views\main.py", line 144, in __init__
    self.queryset = self.get_queryset(request)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\contrib\admin\views\main.py", line 577, in get_queryset
    qs, search_may_have_duplicates = self.model_admin.get_search_results(
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\contrib\admin\options.py", line 1185, in get_search_results
    queryset = queryset.filter(models.Q.create(term_queries))
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1602, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1634, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1461, in build_filter
    return self._add_q(
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1634, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1461, in build_filter
    return self._add_q(
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1634, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1484, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1296, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\.venv\lib\site-packages\django\db\models\sql\query.py", line 1761, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'description_product' into field. Choices are: add_date, count, description, id, image_product, order, price, title
[ERROR   :             django.server] - 2024-01-31 17:14:23,793 : log_message @0212: "GET /admin/app_2/product/?q=Iphone+15 HTTP/1.1" 500 212961
[INFO    :   django.utils.autoreload] - 2024-01-31 17:15:24,898 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-31 17:15:25,460 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-31 17:15:27,894 : log_message @0212: "GET /admin/app_2/product/?q=Iphone+15 HTTP/1.1" 200 13995
[INFO    :             django.server] - 2024-01-31 17:15:27,979 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 17:15:39,713 : log_message @0212: "GET /admin/app_2/product/?q= HTTP/1.1" 200 18533
[INFO    :             django.server] - 2024-01-31 17:15:39,747 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 17:15:53,739 : log_message @0212: "POST /admin/app_2/product/?q= HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 17:15:53,764 : log_message @0212: "GET /admin/app_2/product/?q= HTTP/1.1" 200 18531
[INFO    :             django.server] - 2024-01-31 17:15:53,811 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-31 17:19:33,786 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-31 17:19:37,720 : log_message @0212: "GET /admin/app_2/product/?q= HTTP/1.1" 200 18531
[INFO    :             django.server] - 2024-01-31 17:19:37,747 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 17:19:51,543 : log_message @0212: "GET /admin/app_2/product/1/change/?_changelist_filters=q%3D HTTP/1.1" 200 12284
[INFO    :             django.server] - 2024-01-31 17:19:51,572 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 17:19:54,625 : log_message @0212: "POST /admin/app_2/product/1/change/?_changelist_filters=q%3D HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 17:19:54,650 : log_message @0212: "GET /admin/app_2/product/ HTTP/1.1" 200 18446
[INFO    :             django.server] - 2024-01-31 17:19:54,688 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 17:20:10,082 : log_message @0212: "GET /admin/app_2/client/ HTTP/1.1" 200 11257
[INFO    :             django.server] - 2024-01-31 17:20:10,113 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 17:20:36,228 : log_message @0212: "GET /admin/app_2/client/ HTTP/1.1" 200 11257
[INFO    :             django.server] - 2024-01-31 17:20:36,260 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-31 17:20:36,927 : trigger_reload @0266: C:\Users\roman\Desktop\Work for IT\GeekBrains\seminars\FrameworkDjango_HW\app_2\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-31 17:20:37,584 : run_with_reloader @0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-31 17:20:37,797 : log_message @0212: "GET /admin/app_2/client/ HTTP/1.1" 200 11257
[INFO    :             django.server] - 2024-01-31 17:20:37,839 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 17:20:46,818 : log_message @0212: "GET /admin/app_2/client/?q=8911222 HTTP/1.1" 200 11404
[INFO    :             django.server] - 2024-01-31 17:20:46,852 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 17:21:04,368 : log_message @0212: "GET /admin/app_2/order/ HTTP/1.1" 200 13116
[INFO    :             django.server] - 2024-01-31 17:21:04,399 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 17:21:21,481 : log_message @0212: "GET /admin/app_2/order/1/change/ HTTP/1.1" 200 15152
[INFO    :             django.server] - 2024-01-31 17:21:21,518 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-31 17:21:26,055 : log_message @0212: "POST /admin/app_2/order/1/change/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-31 17:21:26,075 : log_message @0212: "GET /admin/app_2/order/ HTTP/1.1" 200 13383
[INFO    :             django.server] - 2024-01-31 17:21:26,106 : log_message @0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
